language: python
python:
  - "2.7"
# - "3.6"
# command to install dependencies

before_install:
  - sudo apt-get -qq update -y
  - sudo apt-get install -y mpc mpd espeak

install: "pip install -r requirements_ci.txt"
# command to run tests
script: python blindy.pi.py
